site_name: Zak Language Reference
site_url: https://passiomatic.github.io/elm-zak/
repo_url: https://github.com/passiomatic/elm-zak
edit_uri: edit/main/guide/
docs_dir: .
site_dir: ../build/guide
use_directory_urls: false
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Try Zak: https://passiomatic.github.io/elm-zak/try/
  - The language:
      - Lexical structure: language/Lexical.md
      - Values and data types: language/Values.md
      - Execution context: language/Execution.md
      - Statements: language/Statements.md
      - Expressions: language/Expressions.md
      - Tables: language/Tables.md
      - Arrays: language/Arrays.md
      - Functions: language/Functions.md
      - Threads: language/Threads.md
  - Standard library:
      - Array: stdlib/Array.md
      - Debug: stdlib/Debug.md
      - Global functions: stdlib/Global.md
      - Math: stdlib/Math.md
      - Random: stdlib/Random.md
      - String: stdlib/String.md
      - Table: stdlib/Table.md
      - Thread: stdlib/Thread.md
